server.port=8081
spring.application.name=loan-approval
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#spring.camunda.bpm.admin-user.id=demo
#spring.camunda.bpm.admin-user.password=demo
#spring.camunda.bpm.admin-user.first-name=Demo
#
#spring.camunda.bpm.filter.create=All tasks
#spring.camunda.bpm.history-level=full
#spring.camunda.bpm.auto-deployment-enabled=true
#spring.camunda.bpm.default-serialization-format=application/json

